//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocMgmt.Models.EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocStatusView
    {
        public System.Guid PropertyId { get; set; }
        public Nullable<bool> Agreement { get; set; }
        public Nullable<bool> Appraisal { get; set; }
        public Nullable<bool> SiteMap { get; set; }
        public Nullable<bool> Resume { get; set; }
        public Nullable<bool> Paperwork { get; set; }
    }
}
