//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocMgmt.Models.EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> PropertyId { get; set; }
        public string DocType { get; set; }
        public string FileName { get; set; }
        public byte[] DocBlob { get; set; }
    }
}
